### PR TITLE
option to build library in other directory

### PR DESCRIPTION
**Pull request by Jean-Mick**
## Description

The changes include minor fixes and move the build of library inside obj directory.

## Affected parts

- [ x] Library
- [ x] LibTestApp
- [ x] LibPerfApp
- [ ] Other: (please specify)

## Motivation and Context
This allows multiple builds with different options (e.g. SHARED) from the same source directory.

## How Has This Been Tested?

Tested with git status, make clean, make, make install,  with SHARED=y and SHARED=n

Not tested on Windows.

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tkanteck** [comment]
Hello Jean-Mick,
Many thanks for your pull request. I am guessing that in for some reason you need to put output files in one location (obj folder). However, such change would create domino effect for us to update some internal validation tool-chain. Would it be reasonable to have LIBRARY_OUTPUT_LOCATION make environment setting to default to currently used location? This will also give ability to change it, to 'obj' folder, if required.
Thanks,
Tomasz

**Comment by Jean-Mick** [comment]
Hello Tomasz,

OK I'm fine with LIBRARY_OUTPUT_LOCATION, I see the backward compat issue with existing tool.

Thanks,
Jean-Mickael

**Comment by tkanteck** [comment]
Hi Jean-Mickael,
Do you see backward compatibility issue with the library? Could you explain more?
Thanks,
Tomasz

**Comment by Jean-Mick** [comment]
No, I just refer to the issue you mentioned wrt validation tools looking for current location.

**Comment by tkanteck** [comment]
Ahh :) sorry, travelling made me bit slow. Thanks for the explanation.
OK, could you change the default location in the pull request then? Other then this it looks good for merging.
Thanks again!

**Comment by Jean-Mick** [comment]
No problem :-) Yes I will rework the patch to do that.

**Comment by tkanteck** [comment]
Thanks a mil! The patches have been just merged.

**Pull request closed without merging**
