### PR TITLE
Mayhem

### PR DESCRIPTION
**Pull request by ykyle01**
## Affected parts

- [ ] Library
- [ ] Test Application
- [ ] Perf Application
- [ ] Other: (please specify)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tkanteck** [comment]
Hey @ykyle01, 

Thanks for the PR.

Could you shed some light on how this works? I am not familiar with Mayhem. How is it supposed to be triggered on every push or pull request? Is it some sort of clever smoke fuzz test infrastructure?

Is Mayhem free to use for opensource projects?

It also seems that commit 4f2b4ec9d627e2d8650d6890e550340b19c8c3d4 and 3ab5717e05ca134abbce305c1673f7c72adb9643 could be squashed together (the last one corrects the former one).

**Comment by ykyle01** [comment]
Hello!

It will be triggered on every push and pull request through Github actions,
which will build a Docker image and analyze it with Mayhem on every code
change, where Mayhem essentially does all the fuzz testing. I am not sure
if Mayhem is free to use for open source projects.
Sorry that PR was an accident, but I do think Mayhem is interesting. You
should probably not merge that PR. I was just testing a bit with Mayhem on
public repositories for a school hackathon.

Best,
Kyle

**Comment by tkanteck** [comment]
Hello Kyle,
Thanks for coming back with the info.
I agree with you that it is interesting and worth learning more about.
For now, I am going to close this PR. Is that OK?
Thanks,
Tomasz

**Comment by ykyle01** [comment]
Hi Tomas’s,

Sounds good! Sorry about this.

Best,
Kyle

**Comment by tkanteck** [comment]
No problem at all Kyle. Thanks

**Comment by ykyle01** [comment]
Here is some extra resources:
https://github.com/mayhemheroes/hackathon-resources

**Pull request closed without merging**
