### PR TITLE
cmake clenups.

### PR DESCRIPTION
**Pull request by kloczek**
## Description
- skip checking for C++ compiler by specify in cmake project() LANGUAGES C ASM
- fix man pages install path
## Affected parts

- [ ] Library
- [ ] Test Application
- [ ] Perf Application
- [x] Other: cmake

## Motivation and Context
- fix man paes install path
- minimise build env requirements

## How Has This Been Tested?
- patches integrated into my rpm package build

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by diizzyy** [comment]
You probably want to use MANDIR instead of hardcoding it
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs

**Comment by kloczek** [comment]
Yes but that is better than nothing 😋

**Comment by diizzyy** [comment]
Please update your PR it to use ```${CMAKE_INSTALL_MANDIR}``` then :-)

**Comment by mdcornu** [comment]
> You probably want to use MANDIR instead of hardcoding it https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs

Is there any plan to add this in this PR?

**Comment by mdcornu** [comment]
This has been merged in b0d25b8f04d99229dd616a4afe59e1e91f689b4b and d1ff02c90449ba2046e9d0491244fbf7fabc822f. 
Thank you for your contribution.

**Comment by kloczek** [comment]
Thank you

**Pull request closed without merging**
